### ISSUE TITLE
Add Collected Date and Collect Time in CollecteDT

### ISSUE THREAD

**Issue by cbaja** [TransitDigitale/SIMApp#144]
@KeitelDOG at this two fields on the list after an agent add a product in a point de vente.

@KeitelDOG

**Comment by cbaja** [comment]
Dont forget to add the date, the time and the comment field  in the collect  dt.

@KeitelDOG

**Comment by KeitelDOG** [comment]
@Marcedwin0 , I added 2 color also to Produit and Datetime in Pull Request #175 , because it didn't looked nice with too much info when I added the Datetime at te bottom. Feel Free to modify design.
![image](https://cloud.githubusercontent.com/assets/14042152/20494567/859ad306-afeb-11e6-9961-653852a6b2a4.png)

**Comment by cbaja** [comment]
Just fix the bug #176 

@TransitDigitale/transitiondigitale
